name: Run Code

on:

 workflow_dispatch:
 push:
    branches:
      - master

jobs:

  RunSeleniumCode:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout

      uses: actions/checkout@v2


    - name: Run Selenium Tests

      run: |
        mvn test

